Try to give a more helpful error message when parsing has failed
If we've not managed to catch the error during parsing, ford will
often fail when trying to render the output page with a cryptic:

      RuntimeError: 'str object' has no attribute 'meta'

This tries to be a bit more helpful and guide the user to the likely
source of the error (which might still be due to a bug in ford)